Revert revert
unfoldingWord/translation-helps-rcl pull request #71
Opened 2021-09-10 19:40 UTC by mannycolon

## Describe what your pull request addresses

- [ ]

## Test Instructions

- [ ]

2021-09-10 19:43 UTC, mannycolon commented
> @mannycolon seeing a problem on tN: If I edit all of these fields (OccurrenceNote, OccurrenceNumber, SupportReference, Original Quote ) and click save, then only the changes in the last edited field are saved.
> 
> Seeing same problem in twl.

Comment copied from https://github.com/unfoldingWord/translation-helps-rcl/pull/65

2021-09-10 19:44 UTC, mannycolon commented
@PhotoNomad0 comment copied from https://github.com/unfoldingWord/translation-helps-rcl/pull/65

Here is the problem in tN.  Only the change to Occurrence is saved: 

https://user-images.githubusercontent.com/14238574/132554596-eb9f619c-d089-4d0d-809f-aa4ccea89adb.mov

2021-09-15 13:52 UTC, PhotoNomad0 commented
@mannycolon Much improved still seeing some small problems. 
- Scripture highlight is removed on blur after the Original Quote is edited in tN.
- the old original quote is highlighted when I again select the Original Quote for edit

Example:

https://user-images.githubusercontent.com/14238574/133446064-079b72ea-c693-48d3-a689-fc0dfb8aec51.mov

2021-09-16 13:13 UTC, PhotoNomad0 commented
@mannycolon see problem changing support reference does not update tA until after changes saved.


https://user-images.githubusercontent.com/14238574/133618369-f405de72-3d55-4728-8553-95c88d053340.mov

2021-09-16 19:41 UTC, PhotoNomad0 commented
@mannycolon The previous fixes are looking good, but stumbled across a couple of more issues.
1. when I switch between markdown and html views on tA the unsaved changes are lost
2. not obvious in the video, but I tried entering new lines by hitting return 3 times.  It only worked one time after I had typed some text.  Before and after that hitting the return key had no effect.

https://user-images.githubusercontent.com/14238574/133675623-4f2850bf-aba3-4367-8d23-ed081ed97f8c.mov

2021-09-17 01:17 UTC, PhotoNomad0 commented
@mannycolon tA now does not lose changes when you toggle markdown on/off, and tQ works also, but for some reason twa and tN (in notes area) still lose changes when markdown is toggled

2021-09-23 11:31 UTC, PhotoNomad0 commented
@mannycolon it does not warn you to save ta article edits when you navigate to new tNote

https://user-images.githubusercontent.com/14238574/134499536-bde48531-ed4d-4ab8-9215-80626d211de9.mov

2021-09-29 11:22 UTC, PhotoNomad0 commented
@mannycolon This fixes the problem when navigating to new note using arrows in tn. But still a subtle problem when changing support reference that ta edits are lost:

https://user-images.githubusercontent.com/14238574/135258748-81a50057-f4b7-4b7e-94aa-e754b510eb1e.mov

2021-09-29 13:15 UTC, PhotoNomad0 commented
@mannycolon a couple of other items here:
- on edit of occurrence in twl the save icon does not go black, so cannot save change
- after selecting servant from list and then going back to paul, the twa does not open to paul.


https://user-images.githubusercontent.com/14238574/135275503-c3d93845-c907-4b9c-9caf-4e2a98958216.mov

2021-09-29 13:58 UTC, PhotoNomad0 commented
@mannycolon Also see an issue on tN that edit of occurrence or quote does not enable save, so cannot save change

2021-09-30 10:21 UTC, PhotoNomad0 commented
@mannycolon - three of the issues are working now, but this issue from above is still broken:

- [ ]  after selecting servant from list and then going back to paul, the twa does not open to paul.

It seems to be related to having edited the occurrence, and navigating to another word, when I select the original word again, the twa will not switch back until i refresh.  I tried to make another video, but the mouse pointer disappeared halfway through.  Will try again after my men's prayer time.

2021-09-30 12:53 UTC, PhotoNomad0 commented
@mannycolon - After making an edit for paul,  Paul will not display in twa.  Even after saving, it will not show in twa window.  After app refresh, it will display paul in twa.



https://user-images.githubusercontent.com/14238574/135458246-6c50fd1d-226e-4f4f-af57-191657aac48d.mov

2021-10-01 20:20 UTC, PhotoNomad0 commented
new issue: cannot navigate through tn articles on tit 1:1, but i can on 1:2


https://user-images.githubusercontent.com/14238574/135681538-d4ffb513-2c21-4491-8bed-65627dd77098.mov

2021-10-01 20:28 UTC, PhotoNomad0 commented
@mannycolon - seems to be a continuous loop going on.  When I switched to Eph 1:1 saw a warning that the page was slowing down firefox.

2021-10-02 17:58 UTC, PhotoNomad0 commented
Also, Once when I changed verses I could see it rapidly switching between tn 1 and 3.

2021-10-05 11:48 UTC, PhotoNomad0 commented
@mannycolon - Edits of twa articles are easily lost:

https://user-images.githubusercontent.com/14238574/136016560-57f9a5b4-05ba-43d4-aced-9a8b991731aa.mov

2021-10-05 15:38 UTC, mannycolon commented
> @mannycolon - Edits of twa articles do not give warning before moving to different tw. Sorry about the video, looks like mouse pointer disappears mid-way in clip.
> 
>  twa-loss.mov

I can't reproduce this bug

2021-10-05 17:11 UTC, PhotoNomad0 commented
@mannycolon this is getting interesting.  I was able to reproduce the bug, so I decided to do it again while recording.  Then when i was recording, I did not see it again.  Timing related?

2021-10-05 17:43 UTC, PhotoNomad0 commented
@mannycolon Think I found another issues here:
- 0:43 - after making an edit to twa Paul, I try to select servant and get the warning prompt
- 0:57 - I canceled the warning prompt and clicked save of twa article.  Then I selected servant and then selected Paul again.  The twa article for Paul shows old data, it does not show the '#' I added

https://user-images.githubusercontent.com/14238574/136073360-1a01d168-d60a-47ce-b1d5-138674d2957b.mov

2021-10-05 17:45 UTC, PhotoNomad0 commented
@mannycolon Another example where I didn't get prompted navigating away from a twa edit.

https://user-images.githubusercontent.com/14238574/136075497-083a77b5-c69a-4554-939e-0fd882189e93.mov

2021-10-05 17:51 UTC, PhotoNomad0 commented
@mannycolon Third test case here.  Made edit to Paul.  Clicked off the edit and save button did not activate.  I then was able to navigate to servant without warning.

https://user-images.githubusercontent.com/14238574/136076278-0c8e33fa-2dca-4f0d-8d05-72e3b0b0163b.mov

2021-10-05 19:04 UTC, PhotoNomad0 requested changes

2021-10-05 19:07 UTC, mannycolon commented on package.json
> -    "postpublish": "git tag v$npm_package_version && git push origin v$npm_package_version"
No, actually I removed it because if we use yarn we really don't need this script

2021-10-05 19:11 UTC, mannycolon commented on package.json
> -    "postpublish": "git tag v$npm_package_version && git push origin v$npm_package_version"
Actually I just realized yarn runs git tag v$npm_package_version but not git push origin v$npm_package_version

2021-10-05 19:16 UTC, PhotoNomad0 approved these changes

2021-10-05 19:19 UTC, mannycolon commented on package.json
> -    "postpublish": "git tag v$npm_package_version && git push origin v$npm_package_version"
Never mind, yarn supposedly generates a git tag but I tested locally and it did not

2021-10-05 19:20 UTC, merged